### ISSUE TITLE
Address field is not a valid GraphQL field

### ISSUE THREAD

**Issue by mathg** [tdeNL/craft-geoaddress#10]
When using the address field with the GraphQL Api, the output built from the field looks like a GeoAddress model and can't be read from GraphQL. Ideally it would be possible to split the object with subfields to extract.

`{
      "message": "String cannot represent value: instance of tde\\craft\\geoaddress\\models\\GeoAddressModel",
      "extensions": {
        "category": "graphql"
      }
    }`

**Comment by jordikroon** [comment]
LGTM. Thank you for your contribution.
